NAME	= form
SRC		= main.cpp \
			Bureaucrat.cpp \
			Form.cpp
OBJ		= $(SRC:.cpp=.o)
INCLUDE	= Bureaucrat.hpp \
		  Form.hpp
CC		= c++
FLAGS	= -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(FLAGS) -o $(NAME) $(OBJ)

%.o: %.cpp $(INCLUDE)
	$(CC) $(FLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re